### ISSUE TITLE
Deny generics for now

### ISSUE THREAD

**Issue by jonas-schievink** [1aim/from-request#1]
It's tricky to make them work, so right now the generated code just fails to compile. Forbid generics on the type for now.

**Comment by meh** [comment]
Sounds fair, in which cases would you need a generic request tho?

**Comment by jonas-schievink** [comment]
Not sure ¯\_(ツ)_/¯

It's just that it's currently possible to put the derive on a generic enum, but the generated code won't build, so bailing out early would be better.
