### ISSUE TITLE
Handling empty paths

### ISSUE THREAD

**Issue by jonas-schievink** [1aim/from-request#6]
AFAIK `http://example.com` is technically different from `http://example.com/`, the former having an empty path, while the latter has `/`.

We currently reject paths not starting with `/`, but considering this we might want to either allow `""` as the only path that doesn't begin with `/`, or treat them the same (I can't think of any use case that would require them to be handled differently).

**Comment by meh** [comment]
It's different as far as URI parsing is concerned, but it's the same as far as a request is concerned.

```
Request-Line = Method SP Request-URI SP HTTP-Version CRLF
Request-URI = "*" | absoluteURI | abs_path | authority
```

**Comment by jonas-schievink** [comment]
Ah yeah, that's true. In that case this would only be relevant for tests, which we can probably ignore. Handling `*` would be nice though.
